// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBtCvUEyeGcPmFeWCvSngQ-B08QgJZvGw',
    appId: '1:648494801239:web:57e2f5f13245e58a905e12',
    messagingSenderId: '648494801239',
    projectId: 'fir-flutter-codelab-fb96c',
    authDomain: 'fir-flutter-codelab-fb96c.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-fb96c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ9jysUDAX1-z4x3C5MELJSaffDqXTECc',
    appId: '1:648494801239:android:deff49a9cc209488905e12',
    messagingSenderId: '648494801239',
    projectId: 'fir-flutter-codelab-fb96c',
    storageBucket: 'fir-flutter-codelab-fb96c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK9RRaM6ykQtB-ww4-Qc_QJatg-7LbtFY',
    appId: '1:648494801239:ios:2955ace981ca5488905e12',
    messagingSenderId: '648494801239',
    projectId: 'fir-flutter-codelab-fb96c',
    storageBucket: 'fir-flutter-codelab-fb96c.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK9RRaM6ykQtB-ww4-Qc_QJatg-7LbtFY',
    appId: '1:648494801239:ios:2955ace981ca5488905e12',
    messagingSenderId: '648494801239',
    projectId: 'fir-flutter-codelab-fb96c',
    storageBucket: 'fir-flutter-codelab-fb96c.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}